/* Project: dBASEHielp */
/* Generated by HelpNDoc - https://www.helpndoc.com */

#ifndef __dBaseHelp_HEADER__
#define __dBaseHelp_HEADER__

enum {
  HELP_Welcome = 0,
  HELP_Introdution = 1,
  HELP_NewinthisVersion = 2,
  HELP_Gettingstarted = 3,
  HELP_Systemrequierements = 4,
  HELP_OtherHelpResources = 5
};

#endif
