#define YY_CHAR char
#line 1 "E:\\msys64\\mingw64\\bin\\flexskel.cc"
/* A lexical scanner generated by flex */
/* scanner skeleton version:
 * $Header: c:\\Program\040Files\\Development\\CVS\040Repository/flex++/flexskel.cc,v 1.1.1.1 2002/04/13 06:01:32 Bear Exp $
 */
/* MODIFIED FOR C++ CLASS BY Alain Coetmeur: coetmeur(at)icdc.fr */
/* Note that (at) mean the 'at' symbol that I cannot write */
/* because it is expanded to the class name */
/* made at Informatique-CDC, Research&development department */
/* company from the Caisse Des Depots et Consignations */
/* institutional financial group  */

/* theses symbols are added before this file */
/* #define YY_CHAR 'unsigned char' if 8bit or 'char' if 7bit */
/* #define FLEX_DEBUG if debug mode */
#define FLEX_SCANNER
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
/* Old MSC, before c7 */
#ifdef MSDOS
#ifndef _MSDOS
#define _MSDOS
#endif
#endif
/* turboc */
#ifdef __MSDOS__
#ifndef _MSDOS
#define _MSDOS
#endif
#endif

#ifdef __cplusplus
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#ifndef YY_USE_CLASS
#define YY_USE_CLASS
#endif
#ifndef _MSDOS
//# i n c lude <osfcn.h>
#endif
#else   /* ! __cplusplus */
#ifdef __STDC__
#ifdef __GNUC__
#include <stddef.h>
void *malloc( size_t );
void free( void* );
int read();
#else
#include <stdlib.h>
#endif  /* __GNUC__ */
#define YY_USE_PROTOS
#define YY_USE_CONST
#endif  /* __STDC__ */
#endif  /* ! __cplusplus */
#ifdef __TURBOC__
#define YY_USE_CONST
#endif
#include <stdio.h>


/*********************************************/
/* COMPILER DEPENDENT   MACROS               */
/*********************************************/
/* use prototypes in function declarations */
/* the "const" storage-class-modifier is valid */
#ifndef YY_USE_CONST
#define const
#endif
/* use prototypes in function declarations */
#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif


/*********************/
/* parameters        */

/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif
/* size of default input buffer */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) 
#endif

/***********************************/
/* to be redefined for application */

/* returned upon end-of-file */
#define YY_END_TOK 0
/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* code executed at the end of each rule */
#define YY_BREAK break;

/* #define YY_USER_ACTION */
/* #define YY_USER_INIT */


#ifndef YY_USE_CLASS
/* copy whatever the last rule matched to the standard output */
/* cast to (char *) is because for 8-bit chars, yy___text is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yy___text, yy___leng, 1, yy___out )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifdef _MSDOS
#define YY_INPUT(buf,result,max_size) \
	if ( (result = fread(buf,1,max_size,yy___in)) < 0 ) \
	    YY_FATAL_ERROR( "fread() in flex scanner failed" );
#else
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yy___in), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );

#endif
/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 *      if ( something_happens )
 *              YY_FATAL_ERROR( "oops, the something happened" );
 *      else
 *              everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, yy___stderr  ); \
		(void) putc( '\n', yy___stderr  ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1


/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 
#else 
/* c++ */
#define ECHO yy___echo()
#define YY_INPUT(buf,result,max_size) \
	if ( yy___input((char *)buf, result,max_size) < 0 ) \
	    YY_FATAL_ERROR( "YY_INPUT() in flex scanner failed" );

#define YY_FATAL_ERROR(msg) yy___fatal_error(msg)
#define yywrap() yy___wrap()

#endif
/***********************************/
/* not to be changed */
#define YY_NULL 0
#define YY_END_OF_BUFFER_CHAR 0
/* special action meaning "start processing a new file" */
#define YY_NEW_FILE yy___newfile 
/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)



/* % section 1 definitions go here */ 
#line 1 "pascal.ll"
#define INITIAL 0
#define YY_PascalScanner_FLEX_SCANNER
#include "PascalScanner.h"
#line 43 "pascal.ll"
#line 196 "E:\\msys64\\mingw64\\bin\\flexskel.cc"

#define yy___stderr YY_PascalScanner_ERRFILE
#define yy___text YY_PascalScanner_TEXT
#define yy___leng YY_PascalScanner_LENG
#define yy___in YY_PascalScanner_IN
#define yy___out YY_PascalScanner_OUT
#define yy___newfile \
	do \
		{ \
		YY_PascalScanner_INIT_BUFFER( YY_PascalScanner_CURRENT_BUFFER, yy___in ); \
		YY_PascalScanner_LOAD_BUFFER_STATE(); \
		} \
	while ( 0 )
#if YY_PascalScanner_DEBUG != 0
#define yy___flex_debug YY_PascalScanner_DEBUG_FLAG
#endif


#ifdef YY_USE_CLASS

#define yy___echo YY_PascalScanner_ECHO
#define yy___input YY_PascalScanner_INPUT
#define yy___fatal_error YY_PascalScanner_FATAL_ERROR
#define yy___wrap YY_PascalScanner_WRAP

#endif

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yy___text
 */
#define YY_DO_BEFORE_ACTION \
	yy___text = yy_bp; \
/* % code to fiddle yy___text and yy___leng for yymore() goes here */ \
	yy___leng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yy___text */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yy___text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yy___text )



struct yy_buffer_state
    {
    YY_PascalScanner_IFILE  *yy_input_file;

    YY_PascalScanner_CHAR *yy_ch_buf;               /* input buffer */
    YY_PascalScanner_CHAR *yy_buf_pos;      /* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters */
    int yy_buf_size;    

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;          /* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */

#ifndef YY_USE_CLASS

#if YY_PascalScanner_DEBUG != 0
int YY_PascalScanner_DEBUG_FLAG=YY_PascalScanner_DEBUG_INIT;
#endif
#define YY_CURRENT_BUFFER YY_PascalScanner_CURRENT_BUFFER
static YY_BUFFER_STATE YY_PascalScanner_CURRENT_BUFFER;
/* yy_hold_char holds the character lost when yy___text is formed */
static YY_PascalScanner_CHAR yy_hold_char;

static int yy_n_chars;          /* number of characters read into yy_ch_buf */

/* GLOBAL */
YY_PascalScanner_CHAR *yy___text;
int yy___leng;

YY_PascalScanner_IFILE  *yy___in = (YY_PascalScanner_IFILE  *) 0;
YY_PascalScanner_OFILE *yy___out = (YY_PascalScanner_OFILE  *) 0;

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_PascalScanner_CHAR *yy_c_buf_p = (YY_PascalScanner_CHAR *) 0;
static int yy_init = 1;         /* whether we need to initialize */
static int yy_start = 0;        /* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yy___in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_PascalScanner_CHAR c, YY_PascalScanner_CHAR *buf_ptr ));

#else
/* c++ */
#ifndef YY_PascalScanner_ECHO_NOCODE
void YY_PascalScanner_CLASS::yy___echo()
{YY_PascalScanner_ECHO_CODE
}
#endif
#ifndef YY_PascalScanner_INPUT_NOCODE
int  YY_PascalScanner_CLASS::yy___input(char * buffer,int &result,int max_size)
{YY_PascalScanner_INPUT_CODE
}
#endif
#ifndef YY_PascalScanner_FATAL_ERROR_NOCODE
void YY_PascalScanner_CLASS::yy___fatal_error(char *msg)
{YY_PascalScanner_FATAL_ERROR_CODE
}
#endif
#ifndef YY_PascalScanner_WRAP_NOCODE
int  YY_PascalScanner_CLASS::yy___wrap()
{YY_PascalScanner_WRAP_CODE
}
#endif
void YY_PascalScanner_CLASS::yy_initialize()
{
 yy___in=0;yy___out=0;yy_init = 1;
 yy_start=0;
 yy___text=0;yy___leng=0;
 YY_PascalScanner_CURRENT_BUFFER=0;
 yy_did_buffer_switch_on_eof=0;
 yy_c_buf_p=0;yy_hold_char=0;yy_n_chars=0;
#if YY_PascalScanner_DEBUG != 0
 YY_PascalScanner_DEBUG_FLAG=YY_PascalScanner_DEBUG_INIT;
#endif
}

YY_PascalScanner_CLASS::YY_PascalScanner_CLASS(YY_PascalScanner_CONSTRUCTOR_PARAM) YY_PascalScanner_CONSTRUCTOR_INIT
{yy_initialize();
 YY_PascalScanner_CONSTRUCTOR_CODE;
}
YY_PascalScanner_CLASS::~YY_PascalScanner_CLASS() 
{YY_PascalScanner_DESTRUCTOR_CODE;
 if(YY_PascalScanner_CURRENT_BUFFER)
  YY_PascalScanner_DELETE_BUFFER(YY_PascalScanner_CURRENT_BUFFER);
}

#endif


#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

/* % data tables for the DFA go here */ 
#define YY_END_OF_BUFFER 28
typedef int yy_state_type;
static const short int yy_accept[89] =
    {   0,
        1,    1,   28,   25,    1,    2,    2,   25,   25,   17,
       18,   25,   21,   16,   15,   14,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   25,    1,    0,   19,    0,
       23,   21,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,    0,   22,    0,    0,   23,   20,   20,
       20,   20,    7,   20,   20,   20,   20,    9,   24,   20,
       12,   13,   20,   20,   20,   20,   20,   20,    6,    8,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   10,
       20,   11,   20,    3,    5,   20,    4,    0
    } ;

static const YY_CHAR yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    1,    1,    1,    1,    6,    7,
        8,    9,    1,   10,    1,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,    1,
       16,    1,    1,    1,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
        1,    1,    1,    1,   17,    1,   18,   19,   20,   21,

       22,   23,   24,   25,   26,   17,   17,   17,   27,   28,
       29,   30,   17,   31,   32,   33,   34,   35,   17,   17,
       36,   17,   37,    4,   38,    1,    1
    } ;

static const YY_CHAR yy_meta[39] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    3,    1,    1,
        1,    1,    4,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    1,    1
    } ;

static const short int yy_base[94] =
    {   0,
        0,    0,  115,  116,  112,  116,  116,  107,  103,  116,
      116,   99,   97,  116,  116,  116,    0,   17,   15,   81,
       74,   79,   75,   72,   86,   65,  100,   95,  116,   91,
        0,   86,    0,   74,   64,   78,   67,   73,   65,   59,
       62,   59,   58,   50,  116,   78,   78,    0,   59,   62,
       52,   50,    0,   61,   58,   21,   53,    0,  116,   50,
        0,    0,   44,   43,   51,   52,   42,   44,    0,    0,
       45,   48,   46,   46,   28,   22,   19,   15,   21,    0,
       19,    0,   15,    0,    0,   21,    0,  116,   53,   38,
       57,   61,   65

    } ;

static const short int yy_def[94] =
    {   0,
       88,    1,   88,   88,   88,   88,   88,   89,   88,   88,
       88,   88,   88,   88,   88,   88,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   91,   88,   89,   88,   92,
       93,   88,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   91,   88,   92,   88,   93,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   88,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,    0,   88,   88,
       88,   88,   88

    } ;

static const short int yy_nxt[155] =
    {   0,
        4,    5,    6,    7,    4,    8,    9,    4,    4,   10,
       11,   12,   13,   14,   15,   16,   17,   17,   18,   19,
       17,   20,   21,   17,   17,   22,   17,   17,   17,   23,
       17,   24,   17,   17,   25,   17,   26,    4,   34,   36,
       66,   33,   87,   37,   67,   86,   85,   84,   83,   82,
       81,   80,   35,   28,   28,   28,   28,   44,   44,   44,
       44,   46,   46,   79,   46,   48,   78,   48,   48,   77,
       76,   75,   74,   73,   72,   71,   70,   69,   68,   65,
       64,   63,   62,   61,   60,   59,   47,   45,   58,   57,
       56,   55,   54,   53,   52,   51,   50,   49,   32,   47,

       29,   27,   45,   43,   42,   41,   40,   39,   38,   32,
       31,   30,   29,   27,   88,    3,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88
    } ;

static const short int yy_chk[155] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   18,   19,
       56,   90,   86,   19,   56,   83,   81,   79,   78,   77,
       76,   75,   18,   89,   89,   89,   89,   91,   91,   91,
       91,   92,   92,   74,   92,   93,   73,   93,   93,   72,
       71,   68,   67,   66,   65,   64,   63,   60,   57,   55,
       54,   52,   51,   50,   49,   47,   46,   44,   43,   42,
       41,   40,   39,   38,   37,   36,   35,   34,   32,   30,

       28,   27,   26,   25,   24,   23,   22,   21,   20,   13,
       12,    9,    8,    5,    3,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

#if YY_PascalScanner_DEBUG != 0
static const short int yy_rule_linenum[27] =
    {   0,
       45,   46,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   60,   61,   62,   63,   64,   66,   67,
       69,   71,   73,   75,   77,   77
    } ;

#endif
/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#line 376 "E:\\msys64\\mingw64\\bin\\flexskel.cc"
#ifndef YY_USE_CLASS
static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
#else
#define yy_get_previous_state() ((yy_state_type)(yy_get_previous_state_()))
#define yy_try_NUL_trans(c) ((yy_state_type)(yy_try_NUL_trans_(c)))
#endif

#ifndef YY_USE_CLASS
#ifdef YY_PascalScanner_LEX_DEFINED
YY_PascalScanner_LEX_RETURN YY_PascalScanner_LEX ( YY_PascalScanner_LEX_PARAM )
YY_PascalScanner_LEX_PARAM_DEF
#else
YY_DECL
#endif
#else
YY_PascalScanner_LEX_RETURN YY_PascalScanner_CLASS::YY_PascalScanner_LEX ( YY_PascalScanner_LEX_PARAM)

#endif
    {
    register yy_state_type yy_current_state;
    register YY_PascalScanner_CHAR *yy_cp, *yy_bp;
    register int yy_act;

/* % user's declarations go here */ 


/* % end of prolog */ 
#line 401 "E:\\msys64\\mingw64\\bin\\flexskel.cc"

    if ( yy_init )
	{
	 
	 {
	 YY_USER_INIT;
	 }
	if ( ! yy_start )
	    yy_start = 1;       /* first start state */

	if ( ! yy___in )
	    yy___in = YY_PascalScanner_IFILE_DEFAULT;

	if ( ! yy___out )
	    yy___out = YY_PascalScanner_OFILE_DEFAULT;

	if ( YY_PascalScanner_CURRENT_BUFFER )
	    YY_PascalScanner_INIT_BUFFER( YY_PascalScanner_CURRENT_BUFFER, yy___in );
	else
	    YY_PascalScanner_CURRENT_BUFFER = YY_PascalScanner_CREATE_BUFFER( yy___in, YY_BUF_SIZE );

	YY_PascalScanner_LOAD_BUFFER_STATE();
	yy_init=0;
	}

    while ( 1 )         /* loops until end-of-file is reached */
	{
/* % yymore()-related code goes here */ 
#line 429 "E:\\msys64\\mingw64\\bin\\flexskel.cc"
	yy_cp = yy_c_buf_p;

	/* support of yy___text */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

/* % code to set up and find next match goes here */ 
	yy_current_state = yy_start;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 89 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 88 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;
#line 440 "E:\\msys64\\mingw64\\bin\\flexskel.cc"

yy_find_action:
/* % code to find the action number goes here */ 
	yy_act = yy_accept[yy_current_state];
#line 443 "E:\\msys64\\mingw64\\bin\\flexskel.cc"

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:      /* this label is used only to access EOF actions */
#if YY_PascalScanner_DEBUG != 0
	if ( yy___flex_debug )
		{
		if ( yy_act == 0 )
#ifndef YY_PascalScanner_IOSTREAM
			fprintf( yy___stderr , "--scanner backtracking\n" );
#else
			yy___stderr <<"--scanner backtracking"<<endl;
#endif
		else if ( yy_act < YY_END_OF_BUFFER -1 )
#ifndef YY_PascalScanner_IOSTREAM
			fprintf( yy___stderr , 
			 "--accepting rule at line %d (\"%s\")\n",
			 yy_rule_linenum[yy_act], yy___text );
#else
			yy___stderr <<"--accepting rule at line "
                          <<(int)yy_rule_linenum[yy_act]
                          <<" (\""<<(char *)yy___text<<"\")"<<endl;
#endif
		else if ( yy_act == YY_END_OF_BUFFER -1 )
#ifndef YY_PascalScanner_IOSTREAM
			fprintf( yy___stderr , 
			 "--accepting default rule (\"%s\")\n",
			 yy___text );
#else
			yy___stderr <<"--accepting default rule"
                          <<" (\""<<(char *)yy___text<<"\")"<<endl;
#endif
		else if ( yy_act == YY_END_OF_BUFFER )
#ifndef YY_PascalScanner_IOSTREAM
			fprintf( yy___stderr , "--(end of buffer or a NUL)\n" );
#else
			yy___stderr <<"--(end of buffer or a NUL)"<<endl;
#endif
		else
#ifndef YY_PascalScanner_IOSTREAM
			fprintf( yy___stderr , "--EOF\n" );
#else
			yy___stderr <<"--EOF"<<endl;
#endif
		}
#endif
	switch ( yy_act )
	    {
/* % actions go here */ 
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case 1:
#line 45 "pascal.ll"
{ /* empty */ }
	YY_BREAK
case 2:
#line 46 "pascal.ll"
{ line++;   }
	YY_BREAK
case 3:
#line 48 "pascal.ll"
{ return PascalParser::TOK_PROGRAM;    }
	YY_BREAK
case 4:
#line 49 "pascal.ll"
{ return PascalParser::TOK_PROCEDURE;  }
	YY_BREAK
case 5:
#line 50 "pascal.ll"
{ return PascalParser::TOK_FUNCTION;   }
	YY_BREAK
case 6:
#line 51 "pascal.ll"
{ return PascalParser::TOK_BEGIN;      }
	YY_BREAK
case 7:
#line 52 "pascal.ll"
{ return PascalParser::TOK_END;        }
	YY_BREAK
case 8:
#line 53 "pascal.ll"
{ return PascalParser::TOK_CONST;      }
	YY_BREAK
case 9:
#line 54 "pascal.ll"
{ return PascalParser::TOK_VAR;        }
	YY_BREAK
case 10:
#line 55 "pascal.ll"
{ return PascalParser::TOK_STRING;     }
	YY_BREAK
case 11:
#line 56 "pascal.ll"
{ return PascalParser::TOK_INTEGER;    }
	YY_BREAK
case 12:
#line 57 "pascal.ll"
{ return PascalParser::TOK_BYTE;       }
	YY_BREAK
case 13:
#line 58 "pascal.ll"
{ return PascalParser::TOK_CHAR;       }
	YY_BREAK
case 14:
#line 60 "pascal.ll"
{ return PascalParser::SYM_EQUAL;      }
	YY_BREAK
case 15:
#line 61 "pascal.ll"
{ return PascalParser::SYM_SEMICOLON;  }
	YY_BREAK
case 16:
#line 62 "pascal.ll"
{ return PascalParser::SYM_COLON;      }
	YY_BREAK
case 17:
#line 63 "pascal.ll"
{ return PascalParser::SYM_COMMA;      }
	YY_BREAK
case 18:
#line 64 "pascal.ll"
{ return PascalParser::SYM_DOT;        }
	YY_BREAK
case 19:
#line 66 "pascal.ll"
{ val->string_val = strdup( yytext ); return PascalParser::TOK_STRINGEXPR; }
	YY_BREAK
case 20:
#line 67 "pascal.ll"
{ val->string_val = strdup( yytext ); return PascalParser::TOK_IDENTIFIER; }
	YY_BREAK
case 21:
#line 69 "pascal.ll"
{ val->int_val = atoi(yytext); return PascalParser::TOK_CONSTANT;   }
	YY_BREAK
case 22:
#line 71 "pascal.ll"
;
	YY_BREAK
case 23:
#line 73 "pascal.ll"
;
	YY_BREAK
case 24:
#line 75 "pascal.ll"
;
	YY_BREAK
case 25:
#line 77 "pascal.ll"
{
    std::stringstream ss;
    ss << "Ungültiges Zeichen: " << yytext[0];
    val->string_val = strdup( ss.str().c_str() );
    
    return PascalParser::UNKNOWN;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 85 "pascal.ll"
{ yyterminate(); }
	YY_BREAK
case 27:
#line 86 "pascal.ll"
ECHO;
	YY_BREAK
#line 493 "E:\\msys64\\mingw64\\bin\\flexskel.cc"

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yy___text - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &YY_PascalScanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yy___text + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yy___text + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
/* % code to do backtracking for compressed tables and set up yy_cp goes here */ 
			    yy_cp = yy_last_accepting_cpos;
			    yy_current_state = yy_last_accepting_state;
#line 541 "E:\\msys64\\mingw64\\bin\\flexskel.cc"
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yy___text,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yy___text + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yy___text + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yy___text + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &YY_PascalScanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yy___text + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#if YY_PascalScanner_DEBUG != 0
#ifndef YY_PascalScanner_IOSTREAM
		fprintf(yy___stderr , "action # %d\n", yy_act );
#else
		yy___stderr <<"action # "<<(int)yy_act<<endl;
#endif
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
	yyterminate();/* avoid the no return value error message on MS-C7/dos */
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */
#ifndef YY_USE_CLASS
static int yy_get_next_buffer()
#else
int YY_PascalScanner_CLASS::yy_get_next_buffer()
#endif
    {
    register YY_PascalScanner_CHAR *dest = YY_PascalScanner_CURRENT_BUFFER->yy_ch_buf;
    register YY_PascalScanner_CHAR *source = yy___text - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &YY_PascalScanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yy___text;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( YY_PascalScanner_CURRENT_BUFFER->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = YY_PascalScanner_CURRENT_BUFFER->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&YY_PascalScanner_CURRENT_BUFFER->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move - YY_MORE_ADJ == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    YY_PascalScanner_CURRENT_BUFFER->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    YY_PascalScanner_CURRENT_BUFFER->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    YY_PascalScanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    YY_PascalScanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yy___text begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yy___text = &YY_PascalScanner_CURRENT_BUFFER->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

#ifndef YY_USE_CLASS
static yy_state_type yy_get_previous_state()
#else
long YY_PascalScanner_CLASS::yy_get_previous_state_()
#endif
    {
    register yy_state_type yy_current_state;
    register YY_PascalScanner_CHAR *yy_cp;

/* % code to get the start state into yy_current_state goes here */ 
    yy_current_state = yy_start;
#line 717 "E:\\msys64\\mingw64\\bin\\flexskel.cc"

    for ( yy_cp = yy___text + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
/* % code to find the next state goes here */ 
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 89 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
#line 721 "E:\\msys64\\mingw64\\bin\\flexskel.cc"
	}

#ifndef YY_USE_CLASS
    return ( yy_current_state );
#else
    return (long)( yy_current_state );
#endif
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif
#else
long YY_PascalScanner_CLASS::yy_try_NUL_trans_(long yy_current_state_)
#endif

    {
#ifndef YY_USE_CLASS
#else
    yy_state_type yy_current_state=(yy_state_type)yy_current_state_;
#endif
    register int yy_is_jam;
/* % code to find the next state, and perhaps do backtracking, goes here */ 
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 89 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 88);
#line 755 "E:\\msys64\\mingw64\\bin\\flexskel.cc"

#ifndef YY_USE_CLASS
    return ( yy_is_jam ? 0 : yy_current_state );
#else
    return (long)( yy_is_jam ? 0 : yy_current_state );
#endif
    }

#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
static void yyunput( YY_PascalScanner_CHAR c, register YY_PascalScanner_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_PascalScanner_CHAR c;
register YY_PascalScanner_CHAR *yy_bp;
#endif
#else
void YY_PascalScanner_CLASS::yyunput( YY_PascalScanner_CHAR c, YY_PascalScanner_CHAR *yy_bp )
#endif

    {
    register YY_PascalScanner_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yy___text */
    *yy_cp = yy_hold_char;

    if ( yy_cp < YY_PascalScanner_CURRENT_BUFFER->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_PascalScanner_CHAR *dest =
	    &YY_PascalScanner_CURRENT_BUFFER->yy_ch_buf[YY_PascalScanner_CURRENT_BUFFER->yy_buf_size + 2];
	register YY_PascalScanner_CHAR *source =
	    &YY_PascalScanner_CURRENT_BUFFER->yy_ch_buf[number_to_move];

	while ( source > YY_PascalScanner_CURRENT_BUFFER->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = YY_PascalScanner_CURRENT_BUFFER->yy_buf_size;

	if ( yy_cp < YY_PascalScanner_CURRENT_BUFFER->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yy___text again */
    }

#ifndef YY_USE_CLASS
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
#else
int YY_PascalScanner_CLASS::input()
#endif
    {
    int c;
    YY_PascalScanner_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &YY_PascalScanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yy___text = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yy___text + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;
#ifndef YY_USE_CLASS
#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yy___text + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifndef YY_USE_CLASS
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
#else
		    YY_FATAL_ERROR( "unexpected last match in YY_PascalScanner_CLASS::input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_PascalScanner_RESTART( YY_PascalScanner_IFILE  *input_file )
#else
void YY_PascalScanner_RESTART( input_file )
YY_PascalScanner_IFILE  *input_file;
#endif
#else
void YY_PascalScanner_CLASS::YY_PascalScanner_RESTART ( YY_PascalScanner_IFILE  *input_file )
#endif

    {
    YY_PascalScanner_INIT_BUFFER( YY_PascalScanner_CURRENT_BUFFER, input_file );
    YY_PascalScanner_LOAD_BUFFER_STATE();
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_PascalScanner_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer )
#else
void YY_PascalScanner_SWITCH_TO_BUFFER( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
#else
void YY_PascalScanner_CLASS::YY_PascalScanner_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer )
#endif

    {
    if ( YY_PascalScanner_CURRENT_BUFFER == new_buffer )
	return;

    if ( YY_PascalScanner_CURRENT_BUFFER )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	YY_PascalScanner_CURRENT_BUFFER->yy_buf_pos = yy_c_buf_p;
	YY_PascalScanner_CURRENT_BUFFER->yy_n_chars = yy_n_chars;
	}

    YY_PascalScanner_CURRENT_BUFFER = new_buffer;
    YY_PascalScanner_LOAD_BUFFER_STATE();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_PascalScanner_LOAD_BUFFER_STATE( void )
#else
void YY_PascalScanner_LOAD_BUFFER_STATE()
#endif
#else
void YY_PascalScanner_CLASS::YY_PascalScanner_LOAD_BUFFER_STATE(  )
#endif

    {
    yy_n_chars = YY_PascalScanner_CURRENT_BUFFER->yy_n_chars;
    yy___text = yy_c_buf_p = YY_PascalScanner_CURRENT_BUFFER->yy_buf_pos;
    yy___in = YY_PascalScanner_CURRENT_BUFFER->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE YY_PascalScanner_CREATE_BUFFER( YY_PascalScanner_IFILE  *file, int size )
#else
YY_BUFFER_STATE YY_PascalScanner_CREATE_BUFFER( file, size )
YY_PascalScanner_IFILE  *file;
int size;
#endif
#else
YY_BUFFER_STATE YY_PascalScanner_CLASS::YY_PascalScanner_CREATE_BUFFER( YY_PascalScanner_IFILE  *file, int size )
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in YY_PascalScanner_CREATE_BUFFER()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_PascalScanner_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in YY_PascalScanner_CREATE_BUFFER()" );

    YY_PascalScanner_INIT_BUFFER( b, file );

    return ( b );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_PascalScanner_DELETE_BUFFER( YY_BUFFER_STATE b )
#else
void YY_PascalScanner_DELETE_BUFFER( b )
YY_BUFFER_STATE b;
#endif
#else
void YY_PascalScanner_CLASS::YY_PascalScanner_DELETE_BUFFER( YY_BUFFER_STATE b )
#endif

    {
    if ( b == YY_PascalScanner_CURRENT_BUFFER )
	YY_PascalScanner_CURRENT_BUFFER = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_PascalScanner_INIT_BUFFER( YY_BUFFER_STATE b, YY_PascalScanner_IFILE  *file )
#else
void YY_PascalScanner_INIT_BUFFER( b, file )
YY_BUFFER_STATE b;
YY_PascalScanner_IFILE  *file;
#endif
#else
void YY_PascalScanner_CLASS::YY_PascalScanner_INIT_BUFFER( YY_BUFFER_STATE b, YY_PascalScanner_IFILE  *file)
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
#line 86 "pascal.ll"

